name: Bazel

on: [push]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: bazel --bazelrc=/dev/null build //...

    - name: Test
      run: bazel --bazelrc=/dev/null test //...
