name: On Push

on: [push]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ^1.17

    - name: Set up cache
      uses: actions/cache@v2
      with:
        path: |
          ~/bazel-cache
        key: bazel-cache-${{ runner.os }}

    - name: Build
      run: bazel --bazelrc=/dev/null build --disk_cache=~/bazel-cache //...
      shell: bash

    - name: Test
      run: bazel --bazelrc=/dev/null test --disk_cache=~/bazel-cache //...
      shell: bash
