name: On Push

on: [push]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ^1.17

    - name: Build
      run: bazel --bazelrc=/dev/null build //...
      shell: bash

    - name: Test
      run: bazel --bazelrc=/dev/null test //...
      shell: bash
